[Variables]

Language=English
ScrollMouseIncrement=0.01
Hidden=0
Hidden2=1
Color1=153,163,242
Color2=203,209,250
Color3=255,255,255

;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------

Icon0NameAndPath=#@#\Icons\divider-normal.png
TextName0=Divider

Icon1NameAndPath=#@#\Icons\home.png
TextName1=Home
LocationPath1=[C:\Users\trieu]

Icon2NameAndPath=#@#\Icons\downloads.png
TextName2=Downloads
LocationPath2=[C:\Users\trieu\Downloads]

Icon3NameAndPath=#@#\Icons\docs.png
TextName3=Documents
LocationPath3=[C:\Users\trieu\Documents]

Icon4NameAndPath=#@#\Icons\pictures.png
TextName4=Pictures
LocationPath4=[C:\Users\trieu\Pictures]

Icon5NameAndPath=#@#\Icons\kodi.png
TextName5=Programs
LocationPath5=[D:\Program]

Icon6NameAndPath=#@#\Icons\settings.png
TextName6=ControlPanel
LocationPath6=[shell:::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}]

Icon7NameAndPath=#@#\Icons\vscode-line.png
TextName7=VSCode
LocationPath7=["C:\Users\trieu\AppData\Local\Programs\Microsoft VS Code\Code.exe"]

Icon8NameAndPath=#@#\Icons\mail.png
TextName8=Gmail
LocationPath8=[https://mail.google.com/]

Icon9NameAndPath=#@#\Icons\discord.png
TextName9=Discord
LocationPath9=[https://discord.com/channels/@me]

Icon10NameAndPath=#@#\Icons\ubuntu.png
TextName10=Ubuntu
LocationPath10=[explorer "\\wsl.localhost\Ubuntu-22.04\home\yuran1811"]

Icon11NameAndPath=#@#\Icons\figma.png
TextName11=Figma
LocationPath11=[C:\Users\trieu\AppData\Local\Figma\app-116.15.4\Figma.exe]

Icon12NameAndPath=#@#\Icons\illustrator.png
TextName12=Illustrator
LocationPath12=["D:\Program\Adobe\Adobe Illustrator 2022\Support Files\Contents\Windows\Illustrator.exe"]

Icon13NameAndPath=#@#\Icons\fitmoodle.png
TextName13=FITMoodle
LocationPath13=[https://courses.ctda.hcmus.edu.vn/]
